version: "2"
services:
  mariadb:
    image: mariadb-centos7
    container_name: mariadb-centos7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=latin
      - MYSQL_USER=lorem
      - MYSQL_PASSWORD=ipsum
    volumes_from:
      - mariadb-data
  mariadb-data:
    image: mariadb-centos7
    volumes:
      - /var/lib/mysql
      - /var/log/mariadb
    entrypoint: /bin/bash