version: "2"
services:
  mariadb-3309:
    build: ./mariadb
    image: mariadb-centos7
    container_name: mariadb-3309
    ports:
      - 3309:3309
    env_file: ./.env_3309
    volumes_from:
      - mariadb-data-3309
  mariadb-data-3309:
    image: mariadb-centos7
    volumes:
      - /var/lib/mysql
      - /var/log/mariadb
    entrypoint: /bin/bash
  mariadb-3310:
    build: ./mariadb
    image: mariadb-centos7
    container_name: mariadb-3310
    ports:
      - 3310:3310
    env_file: ./.env_3310
    volumes_from:
      - mariadb-data-3310
  mariadb-data-3310:
    image: mariadb-centos7
    volumes:
      - /var/lib/mysql
      - /var/log/mariadb
    entrypoint: /bin/bash

