FROM arizonatribe/centosmariadb
MAINTAINER David Nunez <arizonatribe@gmail.com>

# A range of possible ports, choose the one you want in the `docker run`/`docker-compose.yml`
# and override the `mysqld_safe` below with `mysqld_safe --port=<my chosen port>` in your
# docker-compose.yml or `docker run ... mysqld_safe --port=<my chosen port>`
EXPOSE 3306-3356
